# Generated by Django 3.1.7 on 2021-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='licenseid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_security',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
