# Generated by Django 3.1.7 on 2021-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licgen', '0003_profile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Default'),
        ),
    ]
